# Generated by Django 3.2.3 on 2021-06-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='technical',
            field=models.BooleanField(default=False, verbose_name='technical'),
        ),
    ]
