# Generated by Django 3.2 on 2021-04-10 12:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('baserequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='download.baserequest')),
                ('extensions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None, verbose_name='extensions')),
                ('min_bytes', models.IntegerField(default=0, verbose_name='min bytes')),
            ],
            options={
                'db_table': 'resource_request',
            },
            bases=('download.baserequest',),
        ),
    ]
