# Generated by Django 3.0.2 on 2020-03-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorrentRequest',
            fields=[
                ('baserequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='download.BaseRequest')),
            ],
            options={
                'db_table': 'torrent_request',
            },
            bases=('download.baserequest',),
        ),
    ]
