# Generated by Django 3.2 on 2021-05-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_visual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiovisualrequest',
            name='audio_format',
            field=models.CharField(max_length=20, null=True, verbose_name='audio format'),
        ),
    ]
