# Generated by Django 3.0.2 on 2020-01-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_visual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiovisualrequest',
            name='randd',
            field=models.CharField(default='', max_length=200, verbose_name='randdd'),
            preserve_default=False,
        ),
    ]
