# Generated by Django 3.0.2 on 2020-01-24 19:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pre_processing', 'Pre processing'), ('downloading', 'Downloading'), ('post_processing', 'Post processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15, verbose_name='status')),
                ('url', models.URLField(verbose_name='url')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_download.baserequest_set+', to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'base_request',
            },
        ),
    ]
