# Generated by Django 3.0.2 on 2020-01-25 12:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_baserequest_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('level', models.IntegerField(choices=[(50, 'Critical'), (50, 'Fatal'), (40, 'Error'), (30, 'Warning'), (30, 'Warn'), (20, 'Info'), (10, 'Debug'), (0, '')], default=0, verbose_name='level')),
                ('message', models.TextField(verbose_name='message')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download.BaseRequest', verbose_name='request')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
