# Generated by Django 3.0.2 on 2020-02-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_baserequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baserequest',
            name='modified_at',
            field=models.DateTimeField(verbose_name='modified at'),
        ),
    ]
