# Generated by Django 3.1.3 on 2020-11-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_baserequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baserequest',
            name='data',
            field=models.JSONField(default=dict, verbose_name='data'),
        ),
    ]
