# Generated by Django 3.0.2 on 2020-02-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0003_auto_20200208_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baserequest',
            name='modified_at',
            field=models.DateTimeField(null=True, verbose_name='modified at'),
        ),
    ]
