# Generated by Django 3.2.11 on 2022-03-23 19:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0003_auto_20210521_1725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='RequestLog',
        ),
        migrations.AlterModelTable(
            name='requestlog',
            table='request_log',
        ),
        migrations.CreateModel(
            name='FilesLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('path', models.TextField(verbose_name='path')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download.baserequest', verbose_name='request')),
            ],
            options={
                'db_table': 'files_log',
            },
        ),
    ]
