# Generated by Django 3.2.12 on 2022-04-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0004_auto_20220323_2016'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fileslog',
            index=models.Index(fields=['path'], name='path_idx'),
        ),
    ]
